import java.util.HashMap;
import java.util.Map;

//A class to determine the atomic number of the element entered by the user.
public class Elements {
	
	//Create a hash map to hold the elements's abbreviated name and atomic number.		
	private Map<String,Integer> atomicNums;
	private int elementAtomicNum = 0;
	private String selectedElementName;
	
	//The Elements class constructor, it accepts the elements name and returns the 
	//atomic number for that element.
	public Elements(String elementName){
		selectedElementName = elementName;
		atomicNums = new HashMap<String, Integer>();
		setAtomicNums();
	}
	
	//Return the the requested elements name.
	public String getElementName(){
		return selectedElementName;
	}
	
	//Return the requested elements atomic number from the hash map.
	public int getAtomicNums(){		
		elementAtomicNum = atomicNums.get(selectedElementName);
		return elementAtomicNum;
	}
	
	//Set the elements atomic number according to the users input.
	public void setAtomicNums(){
		atomicNums.put("H", 1);
		atomicNums.put("HYDROGEN", 1);
		atomicNums.put("HE", 2);
		atomicNums.put("HELIUM", 2);
		atomicNums.put("LI", 3);
		atomicNums.put("LITHIUM", 3);
		atomicNums.put("BE", 4);
		atomicNums.put("BERYLLIUM", 4);
		atomicNums.put("B", 5);
		atomicNums.put("BORON", 5);
		atomicNums.put("C", 6);
		atomicNums.put("CARBON", 6);
		atomicNums.put("N", 7);
		atomicNums.put("NITROGEN", 7);
		atomicNums.put("O", 8);
		atomicNums.put("OXYGEN", 8);
		atomicNums.put("F", 9);
		atomicNums.put("FLUORINE", 9);
		atomicNums.put("NE", 10);
		atomicNums.put("NEON", 10);
		atomicNums.put("NA", 11);
		atomicNums.put("SODIUM",11);
		atomicNums.put("MG", 12);
		atomicNums.put("MAGNESIUM", 12);
		atomicNums.put("AL", 13);
		atomicNums.put("ALUMINIUM", 13);
		atomicNums.put("ALUMINUM", 13);
		atomicNums.put("SI", 14);
		atomicNums.put("SILICON", 14);
		atomicNums.put("P", 15);
		atomicNums.put("PHOSPHORUS", 15);
		atomicNums.put("S", 16);
		atomicNums.put("SULFUR", 16);
		atomicNums.put("CL", 17);
		atomicNums.put("CHLORINE", 17);
		atomicNums.put("AR", 18);
		atomicNums.put("ARGON", 18);
		atomicNums.put("K", 19);
		atomicNums.put("POTASSIUM", 19);
		atomicNums.put("CA", 20);
		atomicNums.put("CALCIUM", 20);
		atomicNums.put("SC", 21);
		atomicNums.put("SCANDIUM", 21);
		atomicNums.put("TI", 22);
		atomicNums.put("TITANIUM", 22);
		atomicNums.put("V", 23);
		atomicNums.put("VANADIUM", 23);
		atomicNums.put("CR", 24);
		atomicNums.put("CHROMIUM", 24);
		atomicNums.put("MN", 25);
		atomicNums.put("MANGANESE", 25);
		atomicNums.put("FE", 26);
		atomicNums.put("IRON", 26);
		atomicNums.put("CO", 27);
		atomicNums.put("COBALT", 27);
		atomicNums.put("NI", 28);
		atomicNums.put("NICKEL", 28);
		atomicNums.put("CU", 29);
		atomicNums.put("COPPER", 29);
		atomicNums.put("ZN", 30);
		atomicNums.put("ZINC", 30);
		atomicNums.put("GA", 31);
		atomicNums.put("GALLIUM", 31);
		atomicNums.put("GE", 32);
		atomicNums.put("GERMANIUM", 32);
		atomicNums.put("AS", 33);
		atomicNums.put("ARSENIC", 33);
		atomicNums.put("SE", 34);
		atomicNums.put("SELENIUM", 34);
		atomicNums.put("BR", 35);
		atomicNums.put("BROMINE", 35);
		atomicNums.put("KR", 36);
		atomicNums.put("KRYPTON", 36);
		atomicNums.put("RB", 37);
		atomicNums.put("RUBIDIUM", 37);
		atomicNums.put("SR", 38);
		atomicNums.put("STRONTIUM", 38);
		atomicNums.put("Y", 39);
		atomicNums.put("YTTRIUM", 39);
		atomicNums.put("ZR", 40);
		atomicNums.put("ZIRCONIUM", 40);
		atomicNums.put("NB", 41);
		atomicNums.put("NIOBIUM", 41);
		atomicNums.put("MO", 42);
		atomicNums.put("MOLYBDENUM", 42);
		atomicNums.put("TC", 43);
		atomicNums.put("TECHNETIUM", 43);
		atomicNums.put("RU", 44);
		atomicNums.put("RUTHENIUM", 44);
		atomicNums.put("RH", 45);
		atomicNums.put("RHODIUM", 45);
		atomicNums.put("PD", 46);
		atomicNums.put("PALLADIUM", 46);
		atomicNums.put("AG", 47);
		atomicNums.put("SILVER", 47);
		atomicNums.put("CD", 48);
		atomicNums.put("CADMIUM", 48);
		atomicNums.put("IN", 49);
		atomicNums.put("INDIUM", 49);
		atomicNums.put("SN", 50);
		atomicNums.put("TIN", 50);
		atomicNums.put("SB", 51);
		atomicNums.put("ANTIMONY", 51);
		atomicNums.put("TE", 52);
		atomicNums.put("TELLURIUM", 52);
		atomicNums.put("I", 53);
		atomicNums.put("IODINE", 53);
		atomicNums.put("XE", 54);
		atomicNums.put("XENON", 54);
		atomicNums.put("CS", 55);
		atomicNums.put("CAESIUM", 55);
		atomicNums.put("BA", 56);
		atomicNums.put("BARIUM", 56);
		atomicNums.put("LA", 57);
		atomicNums.put("LANTHANUM", 57);
		atomicNums.put("CE", 58);
		atomicNums.put("CERIUM", 58);
		atomicNums.put("PR", 59);
		atomicNums.put("PRASEODYMIUM", 59);
		atomicNums.put("ND", 60);
		atomicNums.put("NEODYMIUM", 60);
		atomicNums.put("PM", 61);
		atomicNums.put("PROMETHIUM", 61);
		atomicNums.put("SM", 62);
		atomicNums.put("SAMARIUM", 62);
		atomicNums.put("EU", 63);
		atomicNums.put("EUROPIUM", 63);
		atomicNums.put("GD", 64);
		atomicNums.put("GADOLINIUM", 64);
		atomicNums.put("TB", 65);
		atomicNums.put("TERBIUM", 65);
		atomicNums.put("DY", 66);
		atomicNums.put("DYSPROSIUM", 66);
		atomicNums.put("HO", 67);
		atomicNums.put("HOLMIUM", 67);
		atomicNums.put("ER", 68);
		atomicNums.put("ERBIUM", 68);
		atomicNums.put("TM", 69);
		atomicNums.put("THULIUM", 69);
		atomicNums.put("YB", 70);
		atomicNums.put("YTTERBIUM", 70);
		atomicNums.put("LU", 71);
		atomicNums.put("LUTETIUM", 71);
		atomicNums.put("HF", 72);
		atomicNums.put("HAFNIUM", 72);
		atomicNums.put("TA", 73);
		atomicNums.put("TANTALUM", 73);
		atomicNums.put("W", 74);
		atomicNums.put("TUNGSTEN", 74);
		atomicNums.put("RE", 75);
		atomicNums.put("RHENIUM", 75);
		atomicNums.put("OS", 76);
		atomicNums.put("OSMIUM", 76);
		atomicNums.put("IR", 77);
		atomicNums.put("IRIDIUM", 77);
		atomicNums.put("PT", 78);
		atomicNums.put("PLATINUM", 78);
		atomicNums.put("AU", 79);
		atomicNums.put("GOLD", 79);
		atomicNums.put("HG", 80);
		atomicNums.put("MERCURY", 80);
		atomicNums.put("TL", 81);
		atomicNums.put("THALLIUM", 81);
		atomicNums.put("PB", 82);
		atomicNums.put("LEAD", 82);
		atomicNums.put("BI", 83);
		atomicNums.put("BISMUTH", 83);
		atomicNums.put("PO", 84);
		atomicNums.put("POLONIUM", 84);
		atomicNums.put("AT", 85);
		atomicNums.put("ASTATINE", 85);
		atomicNums.put("RN", 86);
		atomicNums.put("RADON", 86);
		atomicNums.put("FR", 87);
		atomicNums.put("FRANCIUM", 87);
		atomicNums.put("RA", 88);
		atomicNums.put("RADIUM", 88);
		atomicNums.put("AC", 89);
		atomicNums.put("ACTINIUM", 89);
		atomicNums.put("TH", 90);
		atomicNums.put("THORIUM", 90);
		atomicNums.put("PA", 91);
		atomicNums.put("PROTACTINIUM", 91);
		atomicNums.put("U", 92);
		atomicNums.put("URANIUM", 92);
		atomicNums.put("NP", 93);
		atomicNums.put("NEPTUNIUM", 93);
		atomicNums.put("PU", 94);
		atomicNums.put("PLUTONIUM", 94);
		atomicNums.put("AM", 95);
		atomicNums.put("AMERICIUM", 95);
		atomicNums.put("CM", 96);
		atomicNums.put("CURIUM", 96);
		atomicNums.put("BK", 97);
		atomicNums.put("BERKELIUM", 97);
		atomicNums.put("CF", 98);
		atomicNums.put("CALIFORNIUM", 98);
		atomicNums.put("ES", 99);
		atomicNums.put("EINSTEINIUM", 99);
		atomicNums.put("FM", 100);
		atomicNums.put("FERMIUM", 100);
		atomicNums.put("MD", 101);
		atomicNums.put("MENDELEVIUM", 101);
		atomicNums.put("NO", 102);
		atomicNums.put("NOBELIUM", 102);
		atomicNums.put("LR", 103);
		atomicNums.put("LAWRENCIUM", 103);
		atomicNums.put("RF", 104);
		atomicNums.put("RUTHERFORDIUM", 104);
		atomicNums.put("DB", 105);
		atomicNums.put("DUBNIUM", 105);
		atomicNums.put("SG", 106);
		atomicNums.put("SEABORGIUM", 106);
		atomicNums.put("BH", 107);
		atomicNums.put("BOHRIUM", 107);
		atomicNums.put("HS", 108);
		atomicNums.put("HASSIUM", 108);
		atomicNums.put("MT", 109);
		atomicNums.put("MEITNERIUM", 109);
		atomicNums.put("DS", 110);
		atomicNums.put("DARMSTADTIUM", 110);
		atomicNums.put("RG", 111);
		atomicNums.put("ROENTGENIUM", 111);
		atomicNums.put("CN", 112);
		atomicNums.put("COPERNICIUM", 112);
		atomicNums.put("UUT", 113);
		atomicNums.put("UNUNTRIUM", 113);
		atomicNums.put("FL", 114);
		atomicNums.put("FLEROVIUM", 114);
		atomicNums.put("UUP", 115);
		atomicNums.put("UNUNPENTIUM", 115);
		atomicNums.put("LV", 116);
		atomicNums.put("LIVERMORIUM", 116);
		atomicNums.put("UUS", 117);
		atomicNums.put("UNUNSEPTIUM", 117);
		atomicNums.put("UUO", 118);
		atomicNums.put("UNUNOCTIUM", 118);
	}	
}